/**
 * Radient AI - Sanitized Agent Card Configuration
 * 
 * Defines the identity, capabilities, input validation schema, and output schema
 * of the Scenario Explorer Agent following A2A standards.
 * 
 * "Implementation details intentionally omitted from the public repository."
 */

export interface AgentCard {
  name: string;
  description: string;
  protocolVersion: string;
  version: string;
  url: string;
  capabilities: {
    streaming: boolean;
    pushNotifications: boolean;
  };
  skills: Array<{
    id: string;
    name: string;
    description: string;
    tags: string[];
  }>;
  inputSchema: Record<string, any>;
  outputSchema: Record<string, any>;
}

export const agentCard: AgentCard = {
  name: 'Radient Scenario Explorer Agent',
  description: 'Generates and ranks future-state radiology operational scenarios',
  protocolVersion: '0.3.0',
  version: '0.1.0',
  url: 'https://scenario-agent-xyz.a.run.app/a2a/jsonrpc',
  capabilities: {
    streaming: false,
    pushNotifications: false,
  },
  skills: [
    {
      id: 'staffing-scenario-exploration',
      name: 'staffing scenario exploration',
      description: 'Explore and evaluate staffing levels, shifts, cross-training, and premium labor scenarios.',
      tags: ['staffing']
    },
    {
      id: 'financial-impact-analysis',
      name: 'financial impact analysis',
      description: 'Forecast cost savings, revenue delta, and ROI for operational scenarios.',
      tags: ['finance']
    }
  ],
  inputSchema: {
    modality: {
      type: 'string',
      required: true,
      description: 'Imaging modality (e.g., CT, MRI, XRAY, ULTRASOUND).'
    },
    goal: {
      type: 'string',
      required: false,
      description: 'Natural language optimization objective.'
    },
    constraints: {
      type: 'string',
      required: false,
      description: 'Operational limits or guidelines.'
    }
  },
  outputSchema: {
    baselineSummary: {
      type: 'object',
      description: 'Summary of current operational state metrics.'
    },
    scenariosEvaluated: {
      type: 'array',
      description: 'Candidate scenarios run through the deterministic calculator.'
    },
    recommendedScenario: {
      type: 'object',
      description: 'The selected optimal scenario details.'
    },
    executiveExplanation: {
      type: 'string',
      description: 'Consultant-style explanation generated by Gemini, explaining trade-offs.'
    }
  }
};
